<?php require 'includes/verify.php'; ?>
<!DOCTYPE html>
<html>
<head lang="en">
	<?php require 'includes/head.php'; ?>
	<title><?php
		require 'includes/glazes.php';
		list($first, $second) = explode('-', substr($_SERVER['REQUEST_URI'], strlen('/glaze-gallery/')));
		echo $glazes[$first] . ' + ' . $glazes[$second];
	?></title>
	<link href="css/tile.css" rel="stylesheet">
	<script src="js/tile-data.js"></script>
	<script src="js/tile.js"></script>
	<script src="js/settings.js"></script>
</head>
<body>
	<?php include 'includes/header.php'; ?>
	<div id="grey">
		<div id="instructions">
			<p>On a computer, mouse over the image to magnify. On a touchscreen, pinch to zoom.</p>
		</div>
	</div>
	<main>
		<!-- generated by tile.js -->
	</main>
	<?php include 'includes/footer.php'; ?>
</body>
</html>