<?php require 'includes/verify.php'; ?>
<!DOCTYPE html>
<html>
<head lang="en">
	<?php require 'includes/head.php'; ?>
	<title>Glaze Gallery</title>
	<link href="css/gallery.css" rel="stylesheet">
	<script src="js/tile-data.js"></script>
	<script src="js/gallery.js"></script>
	<script src="js/settings.js"></script>
</head>
<body>
	<?php include 'includes/header.php'; ?>
	<div id="grey">
		<div id="instructions">
			<p>Glazes can be filtered by first and second dip. Captions are in the format &ldquo;first dip (under) \ second dip (over).&rdquo; Icons indicate if the glaze combination is not food safe <span>(<img src="svg/not-food-safe.svg">)</span>, runny <span>(<img src="svg/runny.svg">)</span>, or if the combination may blister, jump, or crawl <span>(<img src="svg/caution.svg">)</span>. Click images for a larger picture and additional notes.</p>
			<p id="disclaimer"><strong>Disclaimer:</strong> Results will vary based on the thickness of the glaze and the clay, the structure of the piece, how the piece is dipped, etc.</p>
		</div>
	</div>
	<div id="filters">
		<div class="filter">
			<h3>1st dip:</h3>
			<select id="first">
				<!-- generated by gallery.js -->
			</select>
		</div>
		<h3 id="slash">\</h3>
		<div class="filter">
			<h3>2nd dip:</h3>
			<select id="second">
				<!-- generated by gallery.js -->
			</select>
		</div>
	</div>
	<main>
		<!-- generated by gallery.js -->
	</main>
	<?php include 'includes/footer.php'; ?>
</body>
</html>